[project]
name = "streamlit-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.0",
    "plotly>=6.1.2",
    "requests>=2.32.4",
    "streamlit>=1.46.0",
]
